# Generated by Django 5.1.4 on 2024-12-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categorie',
            new_name='category',
        ),
    ]
