# Generated by Django 5.1.4 on 2024-12-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_rename_categorie_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='all',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='await_feedback',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='done',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='in_progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='to_do',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='urgent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
