# Generated by Django 5.1.4 on 2024-12-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_summary_all_summary_await_feedback_summary_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join_app.task'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='all',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='await_feedback',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='done',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='in_progress',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='to_do',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='urgent',
            field=models.IntegerField(null=True),
        ),
    ]
