# Generated by Django 5.1.4 on 2024-12-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_remove_task_subtasks_subtask_task_alter_summary_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join_app.task'),
        ),
    ]
