# Generated by Django 5.1.4 on 2024-12-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_column='email', max_length=254),
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_column='phone', max_length=100),
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(db_column='title', max_length=100),
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='subtaskTitle',
        ),
        migrations.AlterField(
            model_name='task',
            name='column_id',
            field=models.CharField(db_column='column_id', max_length=100),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='column_id',
            new_name='columnID',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.task'),
        ),
    ]
