# Generated by Django 5.1.4 on 2025-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
