# Generated by Django 5.1.4 on 2025-01-07 16:05

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token


def load_inital_contacts(apps, schema_editor):
    call_command('loaddata', 'join_app/initial_data.json')
    guest_user = User(username='gast@test.de', first_name='Gast', last_name='', email='gast@test.de', is_staff=True)
    guest_user.set_password('gast123')
    guest_user.save()
    Token.objects.get_or_create(user=guest_user)


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_alter_contact_lastname'),
    ]

    operations = [
        migrations.RunPython(load_inital_contacts)
    ]
